# Generated by Django 4.2.5 on 2023-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('creator', models.TextField()),
                ('year', models.CharField(max_length=255)),
            ],
        ),
    ]
